app/routes/upload_routes.py
from flask import Flask,  request,  jsonify , Blueprint, render_template
import os

upload_route = Blueprint('upload_route', __name__)

# Create uploads directory if it doesn't exist
os.makedirs('app/static/uploads/videos', exist_ok=True)
os.makedirs('app/static/uploads/images', exist_ok=True)

# showing the uploads page
@upload_route.route('/upload_file')
def upload_page():
    return render_template('file-upload.html')
# Route to handle the file upload, preview, and custom filename
@upload_route.route('/upload_file', methods=['POST'])
def upload():
    if 'file' not in request.files:
        return jsonify({'error': 'No file part'}), 400

    file = request.files['file']
    if file.filename == '':
        return jsonify({'error': 'No selected file'}), 400

    # Get the custom filename provided by the user
    custom_filename = request.form.get('filename')

    # If no custom filename is provided, use the original filename
    if not custom_filename:
        custom_filename = file.filename
        # Get the file extension and append it to the custom filename
        file_extension = os.path.splitext(file.filename)[1].lower()
        new_filename = custom_filename + file_extension
        
    new_filename = custom_filename
    filename = new_filename
    
    # Check if the file is a video or an image and save accordingly
    if file.filename.lower().endswith(('.mp4', '.avi', '.mov')):
        # Save video to the videos folder
        video_filename = os.path.join('app', 'static','uploads', 'videos', new_filename)
        file.save(video_filename)
        video_name = filename
        
        return jsonify({'message': f'Video {video_name} saved', 'output_name': video_name, 'is_video': True}), 200
    
    elif file.filename.lower().endswith(('.png', '.jpg', '.jpeg')):
        # Save image to the images folder
        image_filename = os.path.join('app', 'static', 'uploads', 'images', new_filename)
        print(image_filename)
        file.save(image_filename)
        image_name = filename
        
        return jsonify({'message': f'image {image_name} saved', 'output_name': image_name, 'is_video': False}), 200

    else:
        # Handle unsupported file types
        return jsonify({'error': 'Unsupported file type'}), 400

app/routes/video_routes.py
from flask import Blueprint, render_template, request, jsonify, Response, session, url_for, redirect

import os
import cv2
import uuid
import atexit
import pandas as pd
from app import my_model


video_routes = Blueprint('video_routes', __name__)


# Create directories for frames and videos if they don’t exist
live_video_path = os.path.join('app', 'output', 'videos', 'live-videos')
uploaded_video_path = os.path.join('app', 'static', 'uploads', 'videos')

annotated_video_path = os.path.join('app', 'output', 'videos', 'annotated-videos')
annotated_upload_video_path = os.path.join('app', 'output', 'videos', 'annotated-upload-videos')
frames_path = os.path.join('app', 'output', 'images')

if not os.path.exists(live_video_path):
    os.makedirs(live_video_path)
if not os.path.exists(annotated_video_path):
    os.makedirs(annotated_video_path)
if not os.path.exists(frames_path):
    os.makedirs(frames_path)



# initialize path in case of uploaded video
video_path = None
# Initialize variables for video writer
cap = None
out = None
out2 = None
is_recording = False
is_processing = False
video_filename = ""
video_uid = None
uploaded_video_name = None

path = os.path.join('app', 'output', 'videos')
# Generating unique identifier for each video
def generate_uuid():
    return str(uuid.uuid4())

# Ensuring resources are cleaned upon exit
def cleanup():
    global out, is_recording, cap
    # Stop the recording if it’s active
    print("Server interrupted: stopping recording and releasing resources.")
    if is_recording:
        print("Server interrupted: stopping recording and releasing resources.")
        is_recording = False
        out.release()  # Release VideoWriter to save video
        out = None
        
    if is_processing:
        print("Server interrupted: stopping processing and releasing resources.")
        is_processing = False
    if 'uploaded_video_name' in session:
        session.pop('uploaded_video_name')

    if out2 is not None:
        out2.release()
    

    if cap is not None:
        cap.release()  # Release the camera
    print("Resources have been released.")

# Register the cleanup function to be called on exit
atexit.register(cleanup)

# Start recording for live video
@video_routes.route('/start_video')
def start_video():
    global out, is_recording, video_filename, cap

    if cap is None or not cap.isOpened():
        return jsonify({"Status": "Camera is not initialized or cannot be opened "})


    video_uid = generate_uuid()
    session['video_uid'] = video_uid
   

    if not is_recording:
        is_recording = True
        video_filename = os.path.join('app','output','videos','live-videos', f"video_{video_uid}.mp4")
        fourcc = cv2.VideoWriter_fourcc(*'mp4v')  # Use 'mp4v' codec for .mp4
        frame_width = int(cap.get(cv2.CAP_PROP_FRAME_WIDTH))
        frame_height = int(cap.get(cv2.CAP_PROP_FRAME_HEIGHT))
        # frame_rate = 20
        frame_rate = int(cap.get(cv2.CAP_PROP_FPS))
        out = cv2.VideoWriter(video_filename, fourcc, frame_rate, (frame_width, frame_height))
        if not out.isOpened():
            return jsonify({"status": " Failed to open video writer"})
        return jsonify({"status": "Recording started"})
    else:
        return jsonify({"status": "Already recording"})

# Stop recording For live video
@video_routes.route('/stop_video')
def stop_video():
    global out, out2, is_recording
    print('stop video called')
    if out2 is not None:
        out2.release()
        out2 = None
    if out is not None:
        out.release()
        out = None

    if is_recording:
        is_recording = False
        
        # return jsonify({"status": f"Recording stopped. Video saved as {video_filename}"})
        return jsonify({"status": f"Recording stopped. Video saved "})
    else:
        if cap is not None:
            cap.release()
        
        if 'uploaded_video_name' in session:
            session.pop('uploaded_video_name')
        if 'is_processing' in session:
            session.pop('is_processing')
    

        return jsonify({"status": "Recording not active"})

# Video stream generator
def generate_frames(video_uid):
    
    i = 0
    while True:
        success, frame = cap.read()
        if not success:
            break
        
        img = frame
        # img = cv2.cvtColor(img , cv2.COLOR_BGR2RGB)
        # img = cv2.resize(img, (640, 640))
        

        # loading the model
        # model = torch.hub.load("ultralytics/yolov5", "custom", path="app/model/project_model_kaggle.pt")
        model = my_model()
        results = model(img)
        detections = results.pandas().xyxy[0]
        # print(detections)
        # assign a unique ID to each object 
        detections['id'] = range(1, len(detections) + 1)

        # Save individual frames only if recording is active
        if is_recording:
            file_name = os.path.join( frames_path, f'{video_uid }_frame_{i}.jpg')
            # print(f"{file_name} saved,video file id {video_uid}")
            # cv2.imwrite(file_name, frame)
            i += 1

            color_map = {
                'bike': (0, 255, 0),
                'helmet': (0, 0, 255),
                'no_helmet': (255, 0, 0),
                'number_plate': (255, 255, 0),
                'rider': (0, 255, 255)
            }
            # drawing boundin box
            for index, row in detections.iterrows():

                confidence = row['confidence']
                if confidence < 0.5:
                    continue
                x1 = int(row['xmin'])
                y1 = int(row['ymin'])
                x2 = int(row['xmax'])
                y2 = int(row['ymax'])

                class_name = row['name']
                confidence = row['confidence']

                # get color for the current class
                color = color_map.get(class_name, (0, 0, 0)) # default to black if class not found

                # draw rectangle
                cv2.rectangle(img, (x1,y1), (x2,y2), color, 2)
                # put text
                cv2.putText(img, f'{class_name}: {confidence:.2f}', (x1, y1-10) , cv2.FONT_HERSHEY_SIMPLEX, 1, color , 2)

           
            # Write the frame to the video file
            if out:
                out.write(img)

            # # Encode the frame to JPEG for live streaming
            # top_left = (50, 50)   # (x, y)
            # bottom_right = (200, 200)  # (x, y)

            # # Draw the rectangle on the image
            # # Parameters: image, top-left corner, bottom-right corner, color (BGR), thickness
            # cv2.rectangle(frame, top_left, bottom_right, (0, 255, 0), 2)  # Green color, thickness 2

        ret, buffer = cv2.imencode('.jpg', frame)
        frame = buffer.tobytes()

        # Yield frame to the video feed
        yield (b'--frame\r\n'
               b'Content-Type: image/jpeg\r\n\r\n' + frame + b'\r\n')

@video_routes.route('/video_feed')
def video_feed():
    id = session.get('video_uid')
    print(f"video id : {id}")
    return Response(generate_frames(id), mimetype='multipart/x-mixed-replace; boundary=frame')

# live video read and display on page  step 1
@video_routes.route('/live_detection')
def live_detection():

    global cap 
    # cap = cv2.VideoCapture(1) # for external camera
    cap = cv2.VideoCapture(0) # for web camp

    # unique_id = generate_uuid()
    # print(f"unique id for the video : {unique_id}")
    
    return render_template('live-detection.html')



# section 2
# Dealing with existing videos
# uploaded video read and display on page step 1
@video_routes.route('/upload_video_detection/<filename>')
def upload_video_detection(filename):
    global uploaded_video_name
    uploaded_video_name = filename

    # uploaded_video_path = os.path.join('app', 'static', 'uploads', 'videos', filename)

    print('uploaded video name : ', uploaded_video_name)
    session['uploaded_video_name'] = filename

  
    return render_template('file-upload-detection.html', is_video=True, is_image=False, filename=filename)


# def process_video():

# Start processing for uploaded video
@video_routes.route('/start_upload_video_processing')
def start_upload_video_processing():
    global cap, is_processing, uploaded_video_name
    print(f"uploaded video name : {uploaded_video_name}")
    cap = cv2.VideoCapture(os.path.join(uploaded_video_path, uploaded_video_name))
   
    session['is_processing'] = True

    print(uploaded_video_name)
    if not uploaded_video_name:
        return jsonify({'message': 'could not find uploaded video!'})
    
    # frame_height = int(cap.get(cv2.CAP_PROP_FRAME_HEIGHT))
    # frame_width = int(cap.get(cv2.CAP_PROP_FRAME_WIDTH))
    # frame_rate = int(cap.get(cv2.CAP_PROP_FPS))

    # print(f'Frame height: {frame_height}, Frame width: {frame_width}, Frame rate: {frame_rate}')
    is_processing = session.get('is_processing')
    if is_processing:

        return jsonify({'message': 'Video processing started!', 'status': 'success' }) 
    
    return jsonify({'message': 'Video processing not active', 'status': 'failed'})


@video_routes.route('/processed_result')
def processed_result():
    pass


# peform inference on video
def frame_inference(frame):
    # img = cv2.imread(os.path.join('app/static/uploads/images', filename))
    # preparing image for processing
    img = frame
    # img = cv2.cvtColor(img , cv2.COLOR_BGR2RGB)
    # img = cv2.resize(img, (640, 640))
    

    # loading the model
    # model = torch.hub.load("ultralytics/yolov5", "custom", path="app/model/project_model_kaggle.pt")
    model = my_model()
    results = model(img)
    detections = results.pandas().xyxy[0]
    # print(detections)
    # assign a unique ID to each object 
    detections['id'] = range(1, len(detections) + 1)

    color_map = {
        'bike': (0, 255, 0),
        'helmet': (0, 0, 255),
        'no_helmet': (255, 0, 0),
        'number_plate': (255, 255, 0),
        'rider': (0, 255, 255)
    }

app/templates/about.html
{% extends 'base.html' %}
{% block title %} About {% endblock %}
{% block head %}
    <link rel="stylesheet" href="{{ url_for('static', filename='css/about.css') }}">
{% endblock %}

{% block content %}
    <div class="container">
        <h1>About</h1>
        <p>
            This project is a computer vision application designed to enhance road safety by analyzing images and videos for helmet compliance and rider behavior. 
            Using advanced object detection algorithms powered by OpenCV and related technologies, the system can:
        </p>
        <ul>
            <li>Identify and annotate riders, bikes, helmets, and instances of non-compliance (e.g., no helmet).</li>
            <li>Automatically crop and save regions of interest (ROIs) where violations occur for further analysis or reporting.</li>
            <li>Store and organize detailed information about detected violations, including annotated images and metadata.</li>
        </ul>
        <p>
            The goal of this project is to leverage computer vision techniques to support road safety initiatives, enabling automated monitoring and actionable insights 
            for traffic law enforcement and public awareness campaigns.
        </p>
        <p>
            Key Features:
        </p>
        <ul>
            <li>Support for both video and image inputs.</li>
            <li>Real-time detection and annotation of multiple objects within a frame.</li>
            <li>Scalable and efficient processing pipeline for large datasets.</li>
        </ul>
        <p>
            This project is an example of how artificial intelligence and machine learning can be applied to solve real-world challenges, ensuring better compliance and safety on roads.
        </p>
    </div>
{% endblock %}

app/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title> {% block title %} {% endblock %} </title>

    <!-- css files -->
     <link rel="stylesheet" href="{{ url_for('static', filename='css/nav.css') }}">
     <link rel="stylesheet" href="{{ url_for('static', filename='css/base.css')}}">
     <link rel="stylesheet" href="{{ url_for('static', filename='css/footer.css')}}">

    <!-- additinal scripts for child templates -->
    {% block head %} {% endblock %}
</head>
<body>
    <header>
        {% include 'nav.html' %}
    </header>
    <main>
        {% block content %} {% endblock %}
    </main>
    <footer>
        <p> &copy; 2024 - All rights reserved </p>
    </footer>
    
    <!-- additional scripts for child templates -->
    {% block scripts %} {% endblock %}
</body>
</html>

app/templates/contact.html
{% extends 'base.html' %}
{% block title %} Contact {% endblock %}
{% block head %}
    <link rel="stylesheet" href="{{ url_for('static', filename='css/contact.css') }}">
{% endblock %}
{% block content %}
<div class="container">
    <h1>Contact Us</h1>
    <p>If you have any questions or need support, feel free to reach out using the form below.</p>
    
    <form id="contactForm">
        <div class="form-group">
            <label for="name">Your Name</label>
            <input type="text" id="name" name="name" placeholder="Enter your name" required>
        </div>
        
        <div class="form-group">
            <label for="email">Your Email</label>
            <input type="email" id="email" name="email" placeholder="Enter your email" required>
        </div>
        
        <div class="form-group">
            <label for="message">Message</label>
            <textarea id="message" name="message" rows="5" placeholder="Type your message here" required></textarea>
        </div>
        
        <button type="submit" class="btn">Submit</button>
    </form>

    <div id="responseMessage" style="margin-top: 20px; font-weight: bold; color: green; display: none;"></div>
</div>

<script>
    emaile = document.getElementById('email');
    name = document.getElementById('name');
    message = document.getElementById('message');
    document.getElementById('contactForm').addEventListener('submit', async function (event) {
        event.preventDefault(); // Prevent default form submission

        const formData = new FormData(this); // Collect form data

        try {
            const response = await fetch('/contact', {
                method: 'POST',
                body: formData
            });

            const data = await response.json();
            const messageDiv = document.getElementById('responseMessage');

            if (data.status === 'success') {
                messageDiv.style.display = 'block';
                messageDiv.textContent = data.message;

                // Clear form fields
                name.value = '';
                email.value = '';
                message.value = '';
            }
        } catch (error) {
            alert('An error occurred while sending your message. Please try again.');
        }
    });
</script>
{% endblock %}

app/templates/existing-image-detection.html
{% extends 'base.html' %}

app/templates/file-upload-detection.html
{% extends 'base.html' %}

{% block title %} Traffic Project {% endblock %}

{% block head %}
    <link rel="stylesheet" href="{{url_for('static', filename='css/file-upload-detection.css')}}">
{% endblock %}

{% block content %}
    <a href="#" class="backBtn">Back</a>
    <div class="display-container">
        {% if is_video %}
            
            <div class="original-file">
                <video class="video-controls" controls>
                    <source class="video"  src="{{url_for('static', filename='uploads/videos/' + filename )}}" type="video/mp4">
                    Your browser does not support the video tag.
                </video>
            </div>
            <div class="processed-file">
                 
                <img id="stream" src="#" alt="output stream">
            </div>
        {% elif is_image %}
            
            <div class="original-file">
                <img src="{{url_for('static', filename='uploads/images/' + filename )}}" alt="{{filename}}" >
            </div>
            <div class="processed-file">
                <img id="processedImage" src="#" alt="{{filename}}" >

            </div>
        {% endif %}
    </div>
    <div class="actions">
        {% if is_video %}
            <!-- <a href="{{url_for('video_routes.start_upload_video_processing')}}" class="btn"> Start processing </a> -->
             <button id="startProcessingVideo"> Start Processing </button>
             
             
            <a href="{{url_for('video_routes.processed_result')}}" class="btn"> view results </a>
        {% elif is_image %}
            <button id="startProcessingImage" > Start processing </button>
            <a href="{{url_for('image_routes.processed_result')}}" class="btn"> view results </a>
        {% endif %}
        
    </div>
    <div class="info">
        <div id="message"></div>
    </div>
    <div class="info-container">
        <div class="info">
            <h2>Original File</h2>
            <p>Filename: {{filename}}</p>
            <p>File type: {{filetype}}</p>
            <p>File size: {{filesize}}</p>
        </div>
       
    </div>
    <div>
         
    </div>
{% endblock %}

{% block scripts %}
    <script>
        proccessingVideoBtn = document.getElementById('startProcessingVideo');
        // videoElement = document.getElementById('videoPlayer');
        processingImageBtn = document.getElementById('startProcessingImage');
        processImage = document.getElementById('processedImage');
        videoSource = document.getElementById('videoOutput');
        stream = document.getElementById('stream');

        if (proccessingVideoBtn) {
            proccessingVideoBtn.addEventListener('click',  () => {
                console.log("Processing video");
                stream.src = "{{url_for('video_routes.uploaded_video_processed_feed')}}";
                proccessingVideoBtn.disabled = true;
            });
        } 

        // let file  = "{{ filename | tojson }}"
        let file  = JSON.parse('{{ filename | tojson }}') 
        let static_url = "{{url_for('static',filename='')}}"

       
        if (processingImageBtn) {
            processingImageBtn.addEventListener('click', () => {
                fetch(`/image/process_image/${file}`).then(response => {
                    return response.json();
                }).then(data => {
                    console.log('Image processing response:', data);
                    document.getElementById('message').innerHTML = data.message;
                    processedImage.src = static_url + data.filepath;
                    console.log(processedImage.src);
                }).catch(error => {
                    console.error('Error:', error);
                }); 
            });
        }

       

        // saves the data when user tries to leave or reload the page 
        window.addEventListener('beforeunload', function (e) {
            e.preventDefault();
            // Send a request to stop recording when the user tries to leave or reload the page
            fetch('/video/stop_video')
            .then(response => {
                return response.json();
            }).then(data => {
                console.log('Cleanup response:', data);
            });
        });
        
    </script>
{% endblock %}

app/templates/index.html
{% extends 'base.html' %}

{% block title %} Traffic Project {% endblock %}

{% block head %}
    <link rel="stylesheet" href="{{ url_for('static', filename='css/index.css') }}">
{% endblock %}

{% block content %}
    <div>
        <h1 class="title"> Bike , Rider and Helmet Detection System For Traffic Law Enforcement</h1>
    </div>
    <div class="hero">
        <div class="video-container">
            <video autoplay loop muted>
                <source src="{{ url_for('static', filename='home_video/sample.mp4') }}" type="video/mp4">
                Your browser does not support the video tag.
            </video>
        </div>
    </div>
    <div class="service-options-info">
            <div class="info-option" >
                <h2> Our Services </h2>
                <!-- <img src="{{ url_for('static', filename='img_5.jpg') }}" alt="Image"><br/> -->
                
                <p> Mainly we offer object detection related to motocycle riders safety <br/>     
                    <a href="{{ url_for('about') }}" class="know-more-btn"> Know More about the service </a>

                </p>
            </div>
            <div class="service-options">
                <div class="option">
                    <h3> bike, helmet, rider detection (Live) </h3>
                    <p> You should make sure you have a second camera connected for the service to work. 
                        if your camera is available then you are ready to go 
                    </p>
                    <a href="{{ url_for('video_routes.live_detection') }}" class="btn"> Start Live Detection </a>
                </div>
                <div class="option">
                    <h3> bike, helmet, rider detection (Existing Image / Video File) </h3>
                    <p> You can upload an existing image or video file and then run inference on the image or video file </p>
                    <a href="{{ url_for('upload_route.upload_page') }}" class="btn"> Start Detection on uploaded file </a>
                </div>
            
            </div>
        
    </div>
    <div class="last-box"></div>

    <script>
        document.querySelector('video').addEventListener('contextmenu', function(e) {
            e.preventDefault();  // Disable right-click to prevent fullscreen
        });

    </script>
{% endblock %}

app/templates/live-detection.html
{% extends 'base.html' %}

{% block title %} Live-detection {% endblock %}
{% block head %}
    <link rel="stylesheet" href="{{ url_for('static', filename='css/live-detection.css') }}">
{% endblock %}

{% block content %}
<div class="live-page-container">
    
    <!-- Live video stream -->
     <div class="stream-area">
        <div class="live-video">
            <h2>Live Video </h2>
            <img class="stream" src="{{ url_for('video_routes.video_feed') }}" alt="Video Stream" />
        </div>
        <!-- Buttons to start and stop recording -->
         <div class="stream-controls">
            <button onclick="startRecording()">Start Recording</button>
            <button onclick="stopRecording()">Stop Recording</button>
        </div>
        <!-- Status message area -->
        <div id="status-message" ></div>

    </div>   
    <div class="vid-info">
        <h2>detection info</h2>
    </div>
    
</div>

{% endblock %}

{% block scripts %}
<script>
    // Function to start recording
    function startRecording() {
        fetch('/video/start_video')
            .then(response => response.json())
            .then(data => {
                document.getElementById('status-message').innerText = data.status;
            })
            .catch(error => {
                document.getElementById('status-message').innerText = "Error starting recording";
                console.error("Error:", error);
            });
    }

    // Function to stop recording
    function stopRecording() {
        fetch('/video/stop_video')
            .then(response => response.json())
            .then(data => {
                document.getElementById('status-message').innerText = data.status;
            })
            .catch(error => {
                document.getElementById('status-message').innerText = "Error stopping recording";
                console.error("Error:", error);
            });
    }

    // saves the data when user tries to leave or reload the page 
    window.addEventListener('beforeunload', function (e) {
        e.preventDefault();
        // Send a request to stop recording when the user tries to leave or reload the page
        fetch('/video/stop_video')
        .then(response => {
            return response.json();
        }).then(data => {
            console.log('Cleanup response:', data);
        });
    });
</script>
{% endblock %}

app/templates/nav.html
<nav>
    <ul>
        <li><a href="{{ url_for('home') }}">Home</a></li>
        
        <li><a href="{{ url_for('about') }}">About</a></li>
        <li><a href="{{ url_for('contact') }}">contact</a></li>
    </ul>
</nav>